#
# $Id$
#

include $(RULE_DIR)/Rules.mak

CODE_SUBDIRS = \
					.


C_FLAGS += $(SHARED_CFLAGS)


################################################
####   source file 
################################################

SRC += \
		rql.cpp	\


TARGET_LIB:=libRql

TARGET_LIB_SHARED:=$(TARGET_LIB).so
TARGET_LIB_STATIC:=$(TARGET_LIB).a
		 
LOCAL_ALL:=

include $(ROOT_DIR)/Makefile.post

